export const data = [
  { id: 1, product: "Smartphone" },
  { id: 2, product: "Laptop" },
  { id: 3, product: "Smartwatch" },
  { id: 4, product: "Bluetooth Speaker" },
  { id: 5, product: "Wireless Earbuds" },
  { id: 6, product: "Tablet" },
  { id: 7, product: "Gaming Console" },
  { id: 8, product: "Digital Camera" },
  { id: 9, product: "Smart TV" },
  { id: 10, product: "Drone" },
  { id: 11, product: "VR Headset" },
  { id: 12, product: "Portable Projector" },
  { id: 13, product: "Fitness Tracker" },
  { id: 14, product: "E-Reader" },
  { id: 15, product: "Home Assistant Speaker" },
  { id: 16, product: "Electric Toothbrush" },
  { id: 17, product: "Smart Thermostat" },
  { id: 18, product: "Smart Doorbell" },
  { id: 19, product: "Noise-Canceling Headphones" },
  { id: 20, product: "Wireless Charger" },
  { id: 21, product: "Smart Light Bulb" },
  { id: 22, product: "Robot Vacuum" },
  { id: 23, product: "Dash Cam" },
  { id: 24, product: "Smart Plug" },
  { id: 25, product: "Action Camera" },
  { id: 26, product: "Streaming Stick" },
  { id: 27, product: "Smart Scale" },
  { id: 28, product: "Portable Power Bank" },
  { id: 29, product: "Smart Refrigerator" },
  { id: 30, product: "Electric Scooter" },
  { id: 31, product: "Smart Lock" },
  { id: 32, product: "Digital Photo Frame" },
  { id: 33, product: "Air Purifier" },
  { id: 34, product: "Smart Ceiling Fan" },
  { id: 35, product: "Smart Coffee Maker" },
  { id: 36, product: "Smart Mirror" },
  { id: 37, product: "Smart Garage Door Opener" },
];
